# Map of airport codes to their cities
AIRPORT_TO_CITY = {
    'LHR': 'London',
    'LGW': 'London',
    'STN': 'London',
    'LTN': 'London',
    'LCY': 'London',
    'JFK': 'New York',
    'LGA': 'New York',
    'EWR': 'New York',
    'CDG': 'Paris',
    'ORY': 'Paris',
    'LAX': 'Los Angeles',
    'SFO': 'San Francisco',
    'ORD': 'Chicago',
    'DFW': 'Dallas',
    'ATL': 'Atlanta',
    'DXB': 'Dubai',
    'FRA': 'Frankfurt',
    'AMS': 'Amsterdam',
    'MAD': 'Madrid',
    'BKK': 'Bangkok',
    'SIN': 'Singapore',
    'HND': 'Tokyo',
    'NRT': 'Tokyo',
    'PEK': 'Beijing',
    'PVG': 'Shanghai',
    'SYD': 'Sydney',
    'MEX': 'Mexico City',
    'GRU': 'São Paulo',
    'GIG': 'Rio de Janeiro',
    'YYZ': 'Toronto',
    'YVR': 'Vancouver',
    'IST': 'Istanbul',
    'MUC': 'Munich',
    'FCO': 'Rome',
    'MXP': 'Milan',
    'BCN': 'Barcelona',
    'ZRH': 'Zurich',
    'VIE': 'Vienna',
    'CPH': 'Copenhagen',
    'ARN': 'Stockholm',
    'OSL': 'Oslo',
    'HEL': 'Helsinki',
    'DME': 'Moscow',
    'SVO': 'Moscow',
    'LED': 'St. Petersburg',
    'TLV': 'Tel Aviv',
    'CAI': 'Cairo',
    'JNB': 'Johannesburg',
    'CPT': 'Cape Town',
    'NBO': 'Nairobi',
    'DEL': 'Delhi',
    'BOM': 'Mumbai',
    'HKG': 'Hong Kong',
    'ICN': 'Seoul',
    'KUL': 'Kuala Lumpur',
    'MNL': 'Manila',
    'CGK': 'Jakarta',
    'AKL': 'Auckland',
    'MEL': 'Melbourne',
    'BNE': 'Brisbane',
    'PER': 'Perth',
    'DEN': 'Denver',
    'IAH': 'Houston',
    'MIA': 'Miami',
    'SEA': 'Seattle',
    'PHX': 'Phoenix',
    'LAS': 'Las Vegas',
    'MCO': 'Orlando',
    'BOS': 'Boston',
    'DTW': 'Detroit',
    'MSQ': 'Minsk',
    'LIS': 'Lisbon',
    'OPO': 'Porto',
    'DUB': 'Dublin',
    'EDI': 'Edinburgh',
    'GLA': 'Glasgow',
    'MAN': 'Manchester',
    'BHX': 'Birmingham',
    'NCE': 'Nice',
    'MRS': 'Marseille',
    'LYS': 'Lyon',
    'TLS': 'Toulouse',
    'HAM': 'Hamburg',
    'DUS': 'Dusseldorf',
    'BER': 'Berlin',
    'ATH': 'Athens',
    'WAW': 'Warsaw',
    'PRG': 'Prague',
    'BUD': 'Budapest',
    'OTP': 'Bucharest',
    'SOF': 'Sofia',
    'BEG': 'Belgrade',
    'ZAG': 'Zagreb',
    'SKP': 'Skopje',
    'TIA': 'Tirana',
    'KIV': 'Chisinau',
    'EVN': 'Yerevan',
    'TBS': 'Tbilisi',
    'GYD': 'Baku',
    'ANU': 'Antigua',
    'RAK': 'Marrakech',
    'GVA': 'Geneva',
    'CMF': 'Chambery',
    'MLE': 'Male',
    'CGN': 'Cologne',
    'IOM': 'Isle of Man',
    'LBA': 'Larnaca',
    'TPA': 'Tampa',
    'IAD': 'Washington Dulles',
    'MLA': 'Valletta',
    'GLA': 'Glasgow',
    'LED': 'St. Petersburg',
    'FUE': 'Fuerteventura',
    'IKA': 'Imam Khomeini',
    'CUN': 'Cancun',
    'BWI': 'Baltimore',
    'KBP': 'Kyiv',
    'UVF': 'Saint Lucia',
    'SAN': 'San Diego',
    'CTU': 'Chengdu',
    'MAA': 'Chennai',
    'MRU': 'Mauritius',
    'LCA': 'Larnaca',
    'KWI': 'Kuwait',
    'CNX': 'Chiang Mai',
    'BRI': 'Bari',
    'PMI': 'Palma de Mallorca',
    'AGP': 'Malaga',
    'DBV': 'Dubrovnik',
    'YYC': 'Calgary',
    'SJO': 'San Jose',
    'MEL': 'Melbourne',
    'SJC': 'San Jose',
    'BAH': 'Bahrain',
    'AUH': 'Abu Dhabi',
    'NAP': 'Naples',
    'TXL': 'Berlin Tegel',
    'PHL': 'Philadelphia',
    'ABV': 'Abuja',
    'DOH': 'Doha',
    'BLR': 'Bangalore',
    'ABZ': 'Aberdeen',
    'BSL': 'Basel',
    'NCL': 'Newcastle',
    'NAS': 'Nassau',
    'BGI': 'Bridgetown',
    'IBZ': 'Ibiza',
    'PSA': 'Pisa',
    'ACC': 'Accra',
    'GIB': 'Gibraltar',
    'RUH': 'Riyadh',
    'SVQ': 'Seville',
    'TRN': 'Turin',
    'AUS': 'Austin',
    'PUJ': 'Punta Cana',
    'VCE': 'Venice',
    'OUL': 'Oulu',
    'FNC': 'Funchal',
    'JED': 'Jeddah',
    'YUL': 'Montreal',
    'KIEV': 'Kyiv',
    'SSH': 'Sharm El Sheikh',
    'SNN': 'County Clare',
    'GOA': 'Genoa',
    'LIM': 'Lima',
    'MSY': 'New Orleans',
    'GND': 'Grenada',
    'INN': 'Innsbruck',
    'LAD': 'Luanda',
    'BGI': 'Bridgetown',
    'AMM': 'Amman',
    'BFS': 'Belfast',
    'EZE': 'Buenos Aires',
    'BHD': 'Belfast City',
    'DUR': 'Durban',
    'ALC': 'Alicante',
    'CLT': 'Charlotte',
    'BRU': 'Brussels',
    'BGO': 'Bergen',
    'KGS': 'Kos',
    'BIO': 'Bilbao',
    'KRK': 'Krakow',
    'SXF': 'Berlin Schönefeld',
    'FLR': 'Florence',
    'EBB': 'Entebbe',
    'MCI': 'Kansas City',
    'FAO': 'Faro',
    'PFO': 'Paphos',
    'STR': 'Stuttgart',
    'INV': 'Inverness',
    'BDA': 'Bermuda',
    'CTA': 'Catania',
    'JTR': 'Santorini',
    'RTM': 'Rotterdam',
    'SEL': 'Seoul',
    'SZG': 'Salzburg',
    'SKB': 'St Kitts',
    'GRX': 'Granada'
}

# Map of airport names/keywords to their 3-letter IATA codes
AIRPORT_CODES = {
    'heathrow': 'LHR',
    'gatwick': 'LGW',
    'stansted': 'STN',
    'luton': 'LTN',
    'london city': 'LCY',
    'jfk': 'JFK',
    'laguardia': 'LGA',
    'newark': 'EWR',
    'charles de gaulle': 'CDG',
    'cdg': 'CDG',
    'orly': 'ORY',
    'los angeles': 'LAX',
    'lax': 'LAX',
    'san francisco': 'SFO',
    'sfo': 'SFO',
    'chicago': 'ORD',
    'ord': 'ORD',
    'dallas': 'DFW',
    'dfw': 'DFW',
    'atlanta': 'ATL',
    'atl': 'ATL',
    'dubai': 'DXB',
    'dxb': 'DXB',
    'frankfurt': 'FRA',
    'fra': 'FRA',
    'amsterdam': 'AMS',
    'ams': 'AMS',
    'madrid': 'MAD',
    'mad': 'MAD',
    'bangkok': 'BKK',
    'bkk': 'BKK',
    'singapore': 'SIN',
    'sin': 'SIN',
    'haneda': 'HND',
    'hnd': 'HND',
    'narita': 'NRT',
    'nrt': 'NRT',
    'beijing': 'PEK',
    'pek': 'PEK',
    'shanghai': 'PVG',
    'pvg': 'PVG',
    'sydney': 'SYD',
    'syd': 'SYD',
    'mexico city': 'MEX',
    'mex': 'MEX',
    'sao paulo': 'GRU',
    'gru': 'GRU',
    'rio de janeiro': 'GIG',
    'gig': 'GIG',
    'toronto': 'YYZ',
    'yyz': 'YYZ',
    'vancouver': 'YVR',
    'yvr': 'YVR',
    'istanbul': 'IST',
    'ist': 'IST',
    'munich': 'MUC',
    'muc': 'MUC',
    'rome': 'FCO',
    'fco': 'FCO',
    'milan': 'MXP',
    'mxp': 'MXP',
    'barcelona': 'BCN',
    'bcn': 'BCN',
    'zurich': 'ZRH',
    'zrh': 'ZRH',
    'vienna': 'VIE',
    'vie': 'VIE',
    'copenhagen': 'CPH',
    'cph': 'CPH',
    'stockholm': 'ARN',
    'arn': 'ARN',
    'oslo': 'OSL',
    'osl': 'OSL',
    'helsinki': 'HEL',
    'hel': 'HEL',
    'domodedovo': 'DME',
    'dme': 'DME',
    'sheremetyevo': 'SVO',
    'svo': 'SVO',
    'st. petersburg': 'LED',
    'led': 'LED',
    'tel aviv': 'TLV',
    'tlv': 'TLV',
    'cairo': 'CAI',
    'cai': 'CAI',
    'johannesburg': 'JNB',
    'jnb': 'JNB',
    'cape town': 'CPT',
    'cpt': 'CPT',
    'nairobi': 'NBO',
    'nbo': 'NBO',
    'delhi': 'DEL',
    'del': 'DEL',
    'mumbai': 'BOM',
    'bom': 'BOM',
    'hong kong': 'HKG',
    'hkg': 'HKG',
    'seoul': 'ICN',
    'icn': 'ICN',
    'kuala lumpur': 'KUL',
    'kul': 'KUL',
    'manila': 'MNL',
    'mnl': 'MNL',
    'jakarta': 'CGK',
    'cgk': 'CGK',
    'auckland': 'AKL',
    'akl': 'AKL',
    'melbourne': 'MEL',
    'mel': 'MEL',
    'brisbane': 'BNE',
    'bne': 'BNE',
    'perth': 'PER',
    'per': 'PER',
    'denver': 'DEN',
    'den': 'DEN',
    'houston': 'IAH',
    'iah': 'IAH',
    'miami': 'MIA',
    'mia': 'MIA',
    'seattle': 'SEA',
    'sea': 'SEA',
    'phoenix': 'PHX',
    'phx': 'PHX',
    'las vegas': 'LAS',
    'las': 'LAS',
    'orlando': 'MCO',
    'mco': 'MCO',
    'boston': 'BOS',
    'bos': 'BOS',
    'detroit': 'DTW',
    'dtw': 'DTW',
    'minsk': 'MSQ',
    'msq': 'MSQ',
    'lisbon': 'LIS',
    'lis': 'LIS',
    'porto': 'OPO',
    'opo': 'OPO',
    'dublin': 'DUB',
    'dub': 'DUB',
    'edinburgh': 'EDI',
    'edi': 'EDI',
    'glasgow': 'GLA',
    'gla': 'GLA',
    'manchester': 'MAN',
    'man': 'MAN',
    'birmingham': 'BHX',
    'bhx': 'BHX',
    'nice': 'NCE',
    'nce': 'NCE',
    'marseille': 'MRS',
    'mrs': 'MRS',
    'lyon': 'LYS',
    'lys': 'LYS',
    'toulouse': 'TLS',
    'tls': 'TLS',
    'hamburg': 'HAM',
    'ham': 'HAM',
    'dusseldorf': 'DUS',
    'dus': 'DUS',
    'berlin': 'BER',
    'ber': 'BER',
    'athens': 'ATH',
    'ath': 'ATH',
    'warsaw': 'WAW',
    'waw': 'WAW',
    'prague': 'PRG',
    'prg': 'PRG',
    'budapest': 'BUD',
    'bud': 'BUD',
    'bucharest': 'OTP',
    'otp': 'OTP',
    'sofia': 'SOF',
    'sof': 'SOF',
    'belgrade': 'BEG',
    'beg': 'BEG',
    'zagreb': 'ZAG',
    'zag': 'ZAG',
    'skopje': 'SKP',
    'skp': 'SKP',
    'tirana': 'TIA',
    'tia': 'TIA',
    'chisinau': 'KIV',
    'kiv': 'KIV',
    'yerevan': 'EVN',
    'evn': 'EVN',
    'tbilisi': 'TBS',
    'tbs': 'TBS',
    'baku': 'GYD',
    'gyd': 'GYD',
    'antigua': 'ANU',
    'anu': 'ANU',
    'marrakech': 'RAK',
    'rak': 'RAK',
    'geneva': 'GVA',
    'gva': 'GVA',
    'chambery': 'CMF',
    'cmf': 'CMF',
    'male': 'MLE',
    'mle': 'MLE',
    'cologne': 'CGN',
    'cgn': 'CGN',
    'isle of man': 'IOM',
    'iom': 'IOM',
    'lhr': 'LHR',
    'lgw': 'LGW',
    'stn': 'STN',
    'ltn': 'LTN',
    'lcy': 'LCY',
    'leeds': 'LBA',
    'valencia': 'VLC',
    'luxembourg': 'LUX',
    'bahrain': 'BAH',
    'punta cana': 'PUJ',
    'stavanger': 'SVG',
    'got': 'GOT',
    'tehran': 'IKA',
    'lba': 'LBA',
    'tpa': 'TPA',
    'iad': 'IAD',
    'mla': 'MLA',
    'glasgow': 'GLA',
    'st. petersburg': 'LED',
    'fue': 'FUE',
    'ika': 'IKA',
    'cun': 'CUN',
    'bwi': 'BWI',
    'kbp': 'KBP',
    'uvf': 'UVF',
    'san': 'SAN',
    'ctu': 'CTU',
    'maa': 'MAA',
    'mru': 'MRU',
    'lca': 'LCA',
    'kwi': 'KWI',
    'cnx': 'CNX',
    'bri': 'BRI',
    'pmi': 'PMI',
    'agp': 'AGP',
    'dbv': 'DBV',
    'yyc': 'YYC',
    'sjo': 'SJO',
    'melbourne': 'MEL',
    'sjc': 'SJC',
    'bah': 'BAH',
    'auh': 'AUH',
    'nap': 'NAP',
    'txl': 'TXL',
    'phl': 'PHL',
    'abv': 'ABV',
    'doh': 'DOH',
    'blr': 'BLR',
    'abz': 'ABZ',
    'bsl': 'BSL',
    'ncl': 'NCL',
    'nas': 'NAS',
    'bgi': 'BGI',
    'ibz': 'IBZ',
    'psa': 'PSA',
    'acc': 'ACC',
    'gib': 'GIB',
    'ruh': 'RUH',
    'svq': 'SVQ',
    'trn': 'TRN',
    'aus': 'AUS',
    'puj': 'PUJ',
    'vce': 'VCE',
    'oul': 'OUL',
    'fnc': 'FNC',
    'jed': 'JED',
    'yul': 'YUL',
    'kiev': 'KBP',
    'snn': 'SNN',
    'goa': 'GOA',
    'lima': 'LIM',
    'new orleans': 'MSY',
    'grenada': 'GND',
    'innsbruck': 'INN',
    'luanda': 'LAD',
    'amman': 'AMM',
    'belfast': 'BFS',
    'buenos aires': 'EZE',
    'belfast city': 'BHD',
    'durban': 'DUR',
    'alicante': 'ALC',
    'charlotte': 'CLT',
    'brussels': 'BRU',
    'bergen': 'BGO',
    'kos': 'KGS',
    'bilbao': 'BIO',
    'krakow': 'KRK',
    'berlin schönefeld': 'SXF',
    'florence': 'FLR',
    'entebbe': 'EBB',
    'kansas city': 'MCI',
    'faro': 'FAO',
    'paphos': 'PFO',
    'stuttgart': 'STR',
    'inverness': 'INV',
    'bermuda': 'BDA',
    'catania': 'CTA',
    'santorini': 'JTR',
    'rotterdam': 'RTM',
    'seoul': 'SEL',
    'salzburg': 'SZG',
    'st kitts': 'SKB',
    'granada': 'GRX'
}

# Map of city names to their common airport codes
CITY_TO_AIRPORT = {
    'london': 'LHR',  # Default London airport is Heathrow
    'new york': 'JFK',
    'paris': 'CDG',
    'los angeles': 'LAX',
    'chicago': 'ORD',
    'dallas': 'DFW',
    'atlanta': 'ATL',
    'dubai': 'DXB',
    'frankfurt': 'FRA',
    'amsterdam': 'AMS',
    'madrid': 'MAD',
    'bangkok': 'BKK',
    'singapore': 'SIN',
    'tokyo': 'HND',  # Default Tokyo airport is Haneda
    'beijing': 'PEK',
    'shanghai': 'PVG',
    'sydney': 'SYD',
    'mexico city': 'MEX',
    'sao paulo': 'GRU',
    'rio de janeiro': 'GIG',
    'toronto': 'YYZ',
    'vancouver': 'YVR',
    'istanbul': 'IST',
    'munich': 'MUC',
    'rome': 'FCO',
    'milan': 'MXP',
    'barcelona': 'BCN',
    'zurich': 'ZRH',
    'vienna': 'VIE',
    'copenhagen': 'CPH',
    'stockholm': 'ARN',
    'oslo': 'OSL',
    'helsinki': 'HEL',
    'moscow': 'SVO',  # Default Moscow airport is Sheremetyevo
    'st. petersburg': 'LED',
    'tel aviv': 'TLV',
    'cairo': 'CAI',
    'johannesburg': 'JNB',
    'cape town': 'CPT',
    'nairobi': 'NBO',
    'delhi': 'DEL',
    'mumbai': 'BOM',
    'hong kong': 'HKG',
    'seoul': 'ICN',
    'kuala lumpur': 'KUL',
    'manila': 'MNL',
    'jakarta': 'CGK',
    'auckland': 'AKL',
    'melbourne': 'MEL',
    'brisbane': 'BNE',
    'perth': 'PER',
    'denver': 'DEN',
    'houston': 'IAH',
    'miami': 'MIA',
    'seattle': 'SEA',
    'phoenix': 'PHX',
    'las vegas': 'LAS',
    'orlando': 'MCO',
    'boston': 'BOS',
    'detroit': 'DTW',
    'minsk': 'MSQ',
    'lisbon': 'LIS',
    'porto': 'OPO',
    'dublin': 'DUB',
    'edinburgh': 'EDI',
    'glasgow': 'GLA',
    'manchester': 'MAN',
    'birmingham': 'BHX',
    'nice': 'NCE',
    'marseille': 'MRS',
    'lyon': 'LYS',
    'toulouse': 'TLS',
    'hamburg': 'HAM',
    'dusseldorf': 'DUS',
    'berlin': 'BER',
    'athens': 'ATH',
    'warsaw': 'WAW',
    'prague': 'PRG',
    'budapest': 'BUD',
    'bucharest': 'OTP',
    'sofia': 'SOF',
    'belgrade': 'BEG',
    'zagreb': 'ZAG',
    'skopje': 'SKP',
    'tirana': 'TIA',
    'chisinau': 'KIV',
    'yerevan': 'EVN',
    'tbilisi': 'TBS',
    'baku': 'GYD',
    'antigua': 'ANU',
    'marrakech': 'RAK',
    'geneva': 'GVA',
    'chambery': 'CMF',
    'male': 'MLE',
    'cologne': 'CGN',
    'isle of man': 'IOM',
    'mauritius': 'MRU',
    'County Clare': 'SNN',
    'genoa': 'GOA',
    'lima': 'LIM',
    'new orleans': 'MSY',
    'grenada': 'GND',
    'innsbruck': 'INN',
    'luanda': 'LAD',
    'amman': 'AMM',
    'belfast': 'BFS',
    'buenos aires': 'EZE',
    'belfast city': 'BHD',
    'durban': 'DUR',
    'alicante': 'ALC',
    'charlotte': 'CLT',
    'brussels': 'BRU',
    'bergen': 'BGO',
    'kos': 'KGS',
    'bilbao': 'BIO',
    'krakow': 'KRK',
    'berlin schönefeld': 'SXF',
    'florence': 'FLR',
    'entebbe': 'EBB',
    'kansas city': 'MCI',
    'faro': 'FAO',
    'paphos': 'PFO',
    'stuttgart': 'STR',
    'inverness': 'INV',
    'bermuda': 'BDA',
    'catania': 'CTA',
    'santorini': 'JTR',
    'rotterdam': 'RTM',
    'seoul': 'SEL',
    'salzburg': 'SZG',
    'st kitts': 'SKB',
    'granada': 'GRX'
}

# Standardize city names
city_replacements = {
    'Abuja Nigeria': 'Abuja',
    'Abuja, Nigeria': 'Abuja',
    'Bangalore': 'Bengaluru',
    'Belfast City': 'Belfast',
    'Berlin Schönefeld': 'Berlin',
    'Berlin Tegel': 'Berlin',
    'Dusseldorf': 'Düsseldorf',
    'Duesseldorf': 'Düsseldorf',
    'İStanbul': 'Istanbul',
    'Larnaca': 'Larnaca',
    'Montréal': 'Montreal',
    'Palma De Mallorca': 'Palma',
    'Palma de Mallorca': 'Palma',
    'Rio De Janiero': 'Rio de Janeiro',
    'St Lucia': 'Saint Lucia',
    'St. Lucia': 'Saint Lucia',
    'St Petersburg': 'St. Petersburg',
    'St Petersburgh': 'St. Petersburg',
    'Washington Dc': 'Washington',
    'Washington Dulles': 'Washington',
    'Zürich': 'Zurich'
}

# Standardize city names
city_replacements = {
    'Abuja Nigeria': 'Abuja',
    'Abuja, Nigeria': 'Abuja',
    'Bangalore': 'Bengaluru',
    'Belfast City': 'Belfast',
    'Berlin Schönefeld': 'Berlin',
    'Berlin Tegel': 'Berlin',
    'Dusseldorf': 'Düsseldorf',
    'Duesseldorf': 'Düsseldorf',
    'İStanbul': 'Istanbul',
    'Larnaca': 'Larnaca',
    'Montréal': 'Montreal',
    'Palma De Mallorca': 'Palma',
    'Palma de Mallorca': 'Palma',
    'Rio De Janiero': 'Rio de Janeiro',
    'St Lucia': 'Saint Lucia',
    'St. Lucia': 'Saint Lucia',
    'St Petersburg': 'St. Petersburg',
    'St Petersburgh': 'St. Petersburg',
    'Washington Dc': 'Washington',
    'Washington Dulles': 'Washington',
    'Zürich': 'Zurich'
}

COLUMN_ORDER = [
    'verify', 'date_submitted', 'date_flown',
    'customer_name', 'nationality', 
    'type_of_traveller', 'seat_type',
    'aircraft', 
    'origin_city', 'origin_airport', 
    'destination_city', 'destination_airport', 
    'transit_city', 'transit_airport',
    'seat_comfort', 'cabin_staff_service', 'food_and_beverages', 
    'inflight_entertainment', 'ground_service', 'wifi_and_connectivity', 
    'value_for_money', 'recommended', 'review'
]
